services:
  db:
    image: postgres:15-alpine
    container_name: library_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

  redis:
    image: redis:7-alpine
    container_name: library_redis

  app:
    build: .
    container_name: library_app
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
      - redis

  celery:
    build: .
    container_name: library_celery
    command: >
      sh -c "celery -A library_config worker -l info"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
      - redis

  celery-beat:
    build: .
    container_name: library_celery_beat
    command: >
      sh -c "celery -A library_config beat -l info"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
      - redis

volumes:
  postgres_data: